# Copyright (c) 2021 Synopsys, Inc. All rights reserved worldwide.

name: 'Synopsys Intelligent Security Scan'
description: 'Initiate optimized SAST/SCA scans based on code changes and policy with filtered results for display in GitHub.'
author: 'DevSecOps Team @ Synopsys SIG'
branding:
  icon: 'shield'
  color: 'purple'
inputs:
  ioClientArgs:
    description: 'Additional arguments required for workflow engine arguments'
    required: true
  stage:
    description: 'Additional arguments required for workflow engine arguments'
    required: true
    default: 'IO' # This is either IO or WORKFLOW

runs:
  using: 'node16'
  main: 'index.js'
